apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- rbac.yaml
- service.yaml
- serviceAccount.yaml
- tcp-services-configmap.yaml
- udp-services-configmap.yaml
