version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - run:
          command: terragrunt validate

  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - run:
          name: Deploy if tests pass and branch is Staging
          command: terragrunt plan -out "planfile"

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: terragrunt apply -auto-approve -input=false "planfile"

workflows:
  version: 2
  terraform:
    jobs:
      - validate
      - plan:
          requires:
            - validate
      - apply:
          requires:
            - validate
            - plan
          # filters:
          #   branches:
          #     only: master