version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - run:
          command: |
            mkdir bin
            curl -sSL https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.3/terragrunt_linux_amd64 -o bin/terragrunt
            chmod +x bin/terragrunt

      - run:
          command: |

            cd dns/operationcode.net/
            /root/project/bin/terragrunt validate

      - save_cache:
          key: terragrunt
          paths:
            - bin/terragrunt

  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - restore_cache:
          key: terragrunt
          paths:
            - bin/terragrunt

      - run:
          name: Deploy if tests pass and branch is Staging
          command: |
            cd dns/operationcode.net/
            /root/project/bin/terragrunt plan -out "planfile"

      - save_cache:
          key: terragrunt
          paths:
            - bin/terragrunt
            - planfile

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - restore_cache:
          key: terragrunt
          paths:
            - bin/terragrunt
            - planfile

      - run:
          name: Deploy if tests pass and branch is Master
          command: |
            cd dns/operationcode.net/
            /root/project/bin/terragrunt apply -auto-approve -input=false "planfile"

workflows:
  version: 2
  terraform:
    jobs:
      - validate
      - plan:
          requires:
            - validate
      - apply:
          requires:
            - validate
            - plan
          # filters:
          #   branches:
          #     only: master